### ISSUE TITLE
% operator node issues when no spaces

### ISSUE THREAD

**Issue by bgriffith** [tonyganch/gonzales-pe#108]
Issue on current release and latest beta.

When there are no spaces around the `%` operator (valid SCSS) for instance `@if (5%2) == 3 { }` the parser outputs a node tree of:

<img width="286" alt="screen shot 2015-10-12 at 18 11 03" src="https://cloud.githubusercontent.com/assets/2854338/10433825/044c9456-710d-11e5-92b1-51423c333fca.png">

When there are spaces the node tree is as expected and the `%` is of type `operator`.

<img width="264" alt="screen shot 2015-10-12 at 18 14 32" src="https://cloud.githubusercontent.com/assets/2854338/10433845/41e896b6-710d-11e5-8606-05fffe8269fd.png">

**Comment by tonyganch** [comment]
@bgriffith, `5%2` is not valid scss if you assume it returns 1: `5%` part is treated as percentage in both ruby sass and libsass.
Checked it here: http://sassmeister.com/

**Comment by bgriffith** [comment]
Sorry about that @tonyganch - you're 100% correct! Just tried it myself. `5 %2` and `5 % 2` are valid but anything else isn't.
