### ISSUE TITLE
parseTree.contains enhancement

### ISSUE THREAD

**Issue by DanPurdy** [tonyganch/gonzales-pe#123]
Just a thought..

Looking through the documentation, would it be worthwhile adjusting the functionality of parseTree.contains to return something more than a boolean. More specifically rather than returning a true or false it should return `0` if the node doesn't contain the specified node or returns the count of how many child nodes of that type it finds.

Would be extremely useful for the purposes for which we use parseTree.contains and save having to check a node exists then traversing and counting them. Would really help make parseTree.get more useful too.

**Comment by tonyganch** [comment]
Can you please provide an example when it will be useful?

**Comment by jdalton** [comment]
Hi @DanPurdy!

I'm closing this because unless a PR is created it won't likely be addressed.
If you feel strongly about this request I encourage you to dig in and submit a PR 😸
