### ISSUE TITLE
Compacting Scripts in build.sh Makes Debugging Insane

### ISSUE THREAD

**Issue by shellscape** [tonyganch/gonzales-pe#125]
I'm all for minification / compacting of a script when it's intended for client-side use. We practice that heavily. However, this is a node module. And compacting of minifying the javascript within the package does nothing for performance. It only makes debugging gonzales-pe more difficult.

Humbly requesting you remove the compacting option here: https://github.com/tonyganch/gonzales-pe/blob/dev/scripts/build.sh#L7

**Comment by tonyganch** [comment]
Spring cleaning of issue tracker 🧼

Closing the issue as resolved.
