### ISSUE TITLE
SCSS parser breaks on nested child selectors

### ISSUE THREAD

**Issue by danoc** [tonyganch/gonzales-pe#130]
The following Sass is valid but breaks in `v3.2.1`:

**Fails:**

```
.foo {
  > tr > td {
    color: red;
  }
}
// Parsing error: Please check validity of the block starting from line #2
```

```
.foo {
  > .bar > .hi {
    color: red;
  }
}
```

```
.foo {
  > .bar .hi {
    color: red;
  }
}
```

**Works:** 

```
.foo {
  table > tr > td {
    color: red;
  }
}
```

```
.foo {
  &> tr > td {
    color: red;
  }
}
```

```
.foo {
  > td {
    color: red;
  }
}
```

It seems to break when you start a line with a child selector that goes more than one level deep. (Not sure if I explained that correctly, but the examples should help.)

**Comment by danoc** [comment]
I tried fixing this one but couldn't quite figure it out.

**Comment by newagebegins** [comment]
The following code change fixed the issue for me:

``` diff
diff --git a/src/sass/parse.js b/src/sass/parse.js
index ed72c0d..22b8f94 100644
--- a/src/sass/parse.js
+++ b/src/sass/parse.js
@@ -4358,7 +4358,7 @@ function checkSelector2(i) {
     else break;

     let sa = checkSC(i);
-    if (l = checkCombinator(i)) i += sa + l;
+    if (l = checkCombinator(i + sa)) i += sa + l;
     else break;
   }
```

**Comment by cmcclure** [comment]
Another related failing case is `> * + *`

**Comment by DanPurdy** [comment]
@tonyganch just a note to say I ran all of these through the test page and all are parsing without fatal errors now, we can consider closing it if you're happy they're correctly parsing.

**Comment by bgriffith** [comment]
These are all fixed.
