### ISSUE TITLE
LESS variable assignment with tilde - False ParseError

### ISSUE THREAD

**Issue by shellscape** [tonyganch/gonzales-pe#132]
Given the following input:

``` less
@viewport-superwide: ~"(min-width: 1320px)";
```

A ParseError is thrown. This is another false error on valid LESS syntax since 3.0.0-beta. The solution is as follows in `lib/parse.js`:

``` javascript
/**
 * @param {Number} i Token's index number
 * @returns {Number}
 */
function checkTset(i) {
  var l;

  if (l = checkVhash(i)) tokens[i].tset_child = 1;
  else if (l = checkAny(i)) tokens[i].tset_child = 2;
  else if (l = checkSC(i)) tokens[i].tset_child = 3;
  else if (l = checkOperator(i)) tokens[i].tset_child = 4;
  // this is the fix
  // gonzales-pe calls ~"..." an "escaped string" but it's really a strip-quotes directive.
  else if (l = checkEscapedString(i)) tokens[i].tset_child = 5;

  return l;
}

/**
 * @returns {Array}
 */
function getTset() {
  var childType = tokens[pos].tset_child;
  if (childType === 1) return getVhash();
  else if (childType === 2) return getAny();
  else if (childType === 3) return getSC();
  else if (childType === 4) return getOperator();
  // and then we have to account for the new type here
  else if (childType === 5) return getEscapedString();
}
```

Haven't gotten favorable turn-around on the 3 pull requests for other false-positive errors, so I'll leave this for the project collaborators to patch. (They may be busy with life, it happens, but we needed the fixes immediately and as a result our fork is too far ahead to create another PR). Hopefully others that have the same issue will benefit from this info!

**Comment by simoami** [comment]
I came across this as well. Can the maintainer look into it?

**Comment by shellscape** [comment]
@simoami we've opted to switch from gonzales-pe to postcss + postcss-less
