### ISSUE TITLE
SCSS regressions from v3.0.0

### ISSUE THREAD

**Issue by gmac** [tonyganch/gonzales-pe#134]
All these parsing ops worked in 3.0.0, but fail in 3.2.1:

Trailing commas before blocks (permissible by Sass):

```
// >>>>>   h2, {
h2, {
  color: red;
}
```

Keyframes lists:

```
// >>>>>   0%, 80%, 100% {
@keyframes hourglass {
  0%, 80%, 100% {
    color: red;
  }
}
```

Parent reference + interpolation:

```
// >>>>>     &__depth-#{$d} {
$d: 10;
.thing {
  &__depth-#{$d} {
    color: red;
  }
}
```

**Comment by bgriffith** [comment]
Just to note that all these appear to be fixed in the latest version - 3.2.6

**Comment by tonyganch** [comment]
The last two issues appear to be fixed in dev, the first one is still reproducible.

**Comment by bgriffith** [comment]
#237 Fixes the trailing comma issue in `SCSS` but not `Sass`
