### ISSUE TITLE
LESS: Interpolated variable in selector ParseError

### ISSUE THREAD

**Issue by shellscape** [tonyganch/gonzales-pe#135]
The following block is throwing a ParseError:

``` css
&:hover .@{NAMESPACE}-commands-add-recommended {
   .sans-strong();
}
```

**Comment by jdalton** [comment]
Looks related to #75

**Comment by shellscape** [comment]
FWIW I switched to PostCSS about two years ago and utilize their AST these days. Kudos for going through ancient issues.
