### ISSUE TITLE
SCSS parser breaks on parent selector with interpolation

### ISSUE THREAD

**Issue by danoc** [tonyganch/gonzales-pe#136]
This example fails.

```
&#{$var} {}
```

I believe I've found a fix and will submit a PR.

**Comment by rbelling** [comment]
Same issue here: gonzales is breaking when parsing this snippet.

$diff-size: strip-unit($max-size - $min-size); //e.g. 13
$diff-range: $upper-range - $lower-range;
#{$property}: calc(#{$min-size} + #{$diff-size} \* ((100vw - #{$lower-range}px) / #{$diff-range}));

@include width-under($lower-range) {
    #{$property}: $min-size;
}
@include width-over($upper-range) {
    #{$property}: $max-size;
}

**Comment by colin-marshall** [comment]
I am experiencing the same problem as @rbelling, which is slightly different than the original issue (selector vs. property) so I have opened a new issue here: #140.

**Comment by tonyganch** [comment]
Should be fixed in `dev`, will publish a release in a few hours.

**Comment by tonyganch** [comment]
Please check in `@3.2.3`.
