### ISSUE TITLE
SCSS parser breaks on property with interpolation

### ISSUE THREAD

**Issue by colin-marshall** [tonyganch/gonzales-pe#140]
Similar to #136, except with interpolation on a property.

Example:

``` scss
.class {
    margin-#{$global-margin}: 1em;
}
```

**Comment by tonyganch** [comment]
Should be fixed in `dev`, will publish a release in a few hours.

**Comment by colin-marshall** [comment]
Great! Thank you!!!

**Comment by tonyganch** [comment]
Please check in `@3.2.3`.
