### ISSUE TITLE
ParsingError: message property should be writable

### ISSUE THREAD

**Issue by haoqunjiang** [tonyganch/gonzales-pe#143]
When running test for csscomb.js, I got a lot of error messages saying

> `TypeError: Cannot set property message of [object Object] which has only a getter`

That's because [csscomb-core would try to overwrite the `message` property](https://github.com/csscomb/core/blob/dev/src/core.js#L312). But I don't think that's csscomb-core's fault, because the `message` property in a typical `Error` object should be writable and that should be the expected behavior of the `ParsingError` class.

**Comment by haoqunjiang** [comment]
P.S. I don't quite understand what's the point of assigning `message` to `e.stack` in csscomb-core…

The commit message says:

> Set `e.stack` to display errors thrown by binary

But what does "errors thrown by binary" mean?

**Comment by tonyganch** [comment]
Consider this example. You have an invalid css file with content: `a {`.
When you run csscomb as a command line tool, it fails and node reports the error. The error message is taken not from `e.message` field however but from `e.stack`.
So here are two cases.
1) With `e.stack = e.message = ...`:

``` bash
$ cd csscomb.js
$ echo 'a {' > tmp.css
$ ./bin/csscomb tmp.css
stack:  path/to/csscomb.js/tmp.css
Please check the validity of the block starting from line #1

1*| a {

Gonzales PE version: 3.0.0-28
Syntax: css
CSScomb Core version: 3.0.0-3
```

2) Without `e.stack`, just `e.message = ...`:

``` bash
$ cd csscomb.js
$ echo 'a {' > tmp.css
$ ./bin/csscomb tmp.css
stack:  undefined
```

"Errors thrown by binary" means errors that we get while running csscomb from terminal, not as a js module used from some other code.

**Comment by tonyganch** [comment]
Please install GPE from `dev` branch and tell me whether the problem remains.
