### ISSUE TITLE
Sass - !global causes parse error

### ISSUE THREAD

**Issue by bgriffith** [tonyganch/gonzales-pe#148]
Hi @tonyganch - Another one for you!

Using `!global` causes a parse error `Please check the validity of the block starting from line....` with Sass syntax (ok with SCSS)

Example code

``` sass
$bar: orange !global
```

**Comment by tonyganch** [comment]
Should be fixed in `dev`.

**Comment by tonyganch** [comment]
Please check in `@3.2.4` or later.
