### ISSUE TITLE
SCSS Issue with using !important in a mixin call

### ISSUE THREAD

**Issue by raemadeline** [tonyganch/gonzales-pe#168]
I get a parse error wherever there is a mixin call with `!important` as part of the argument like this

```
.no-transitions {
  @include transition(none !important);
}
```

**Comment by bgriffith** [comment]
Thanks for the report, confirmed on both Sass and SCSS.

**Comment by jeffkamo** [comment]
What's the status of this issue? This issue sounds a lot like the issue I [describe in this thread](https://github.com/sasstools/sass-lint/issues/810#issuecomment-237472180).

**Comment by mmase** [comment]
Following for https://github.com/sasstools/sass-lint/issues/898#issuecomment-255267886
