### ISSUE TITLE
SCSS Multiple string interpolation issue

### ISSUE THREAD

**Issue by DanPurdy** [tonyganch/gonzales-pe#169]
As reported in
https://github.com/sasstools/sass-lint/issues/644

The following cause the parser to fail

Example:
https://github.com/zurb/foundation-sites/blob/develop/scss/grid/_classes.scss#L85
https://github.com/zurb/foundation-sites/blob/develop/scss/grid/_flex-grid.scss#L195

``` scss
.#{$-zf-size}-#{$i} { }
```

Here's a slightly different string interpolation that also throws a fatal error:
https://github.com/zurb/foundation-sites/blob/develop/scss/grid/_layout.scss#L25

``` scss
&:nth-of-type(#{$n}n+1) { }
```

Interestingly, the 3 interpolated strings in one line here don't break the parser:
https://github.com/zurb/foundation-sites/blob/develop/scss/grid/_classes.scss#L70

``` scss
.#{$column}.#{$row}.#{$row} { }
```

**Comment by colin-marshall** [comment]
Judging by #171, and the fact that 3 string interpolations works, the hyphen is probably causing the issue in the first two examples, not the double string interpolation.

**Comment by nmcclay** [comment]
I also encountered this issue after updating today, is there any work around for this issue?
```
#{$btn-namespace}-#{$btn-name} {
        @include button($btn-color-set);
    }
```

**Comment by scottyeck** [comment]
FWIW, as per discussion with @colin-marshall, this can be replicated with the `+` token as well.

Hoping this is productive. Otherwise, sorry for the unnecessary communication bloat.

**Comment by DanPurdy** [comment]
This is parsing correctly now, closing.
