### ISSUE TITLE
SASS: Does not take mixins in url()

### ISSUE THREAD

**Issue by varya** [tonyganch/gonzales-pe#187]
Related to this issue: https://github.com/SC5/sc5-styleguide/issues/931

This code gives an error.

```
  &--flyout {
    > a {
      &:after {
        content: ">";
        background:url(bruk-bonus-icon(red)) center right no-repeat;
```

Whereas the same mixin work OK if outside `url()`

```
  &--flyout {
    > a {
      &:after {
        content: ">";
        color: bruk-bonus-icon(red));
```

**Comment by bgriffith** [comment]
Hey @varya - thanks for the report. Could you verify which version of gonzales-pe you are using? Thanks.

**Comment by varya** [comment]
The last one, 3.3.4.

**Comment by bgriffith** [comment]
This is fixed.
