### ISSUE TITLE
Implementation of map, filter, reduce, sort functions when performing tree manipulations.

### ISSUE THREAD

**Issue by srowhani** [tonyganch/gonzales-pe#188]
Would be nice to have these features.

**Comment by tonyganch** [comment]
Can you please describe specs for each of them? Example of how you would like to use them and how they should work.

**Comment by srowhani** [comment]
Take `sort` for example, manipulate the ordering of a set of nodes.

```
   root.sort('declarations', function(prev, curr){
      return prev.toString().localeCompare(curr.toString());
   });
```

Map could be used to return a new tree, after applying a given function to manipulate each element.

Filter would return a new tree with nodes that meet a certain condition.

Reduce, as an accumulate function of sorts. 

Just a suggestion, let me know what you think.
