### ISSUE TITLE
[Sass] Suspected Infinite loop with functions

### ISSUE THREAD

**Issue by DanPurdy** [tonyganch/gonzales-pe#189]
As reported [here](https://github.com/sasstools/sass-lint/issues/732)

the following causes a suspected infinite loop

``` Sass
@function closestEvenNumber($number)
  @if ($number % 2 == 0px)
    @return $number
  @else
    @return ($number + 1px)
```

**Comment by DanPurdy** [comment]
This is another example of this issue

``` scss
@mixin keyframes ($) {
  color: red;
}
```

The dollar sign alone is causing the problem which isn't valid but this should throw a parse error rather than the infinite loop.

**Comment by glen-84** [comment]
This issue makes it impossible to use sass-lint lint-on-type extensions.

@tonyganch Will you be able to take a look at this soon?

**Comment by mimamuh** [comment]
Hi, we have a similar issue when writing long sass class names and a bracket follows a hyphen without whitespace between like this:
.my-very-long-class-name-{}
Then atom freezes.

**Comment by tonyganch** [comment]
@MiMaMuh, I can't reproduce the issue with `.my-very-long-class-name-{}` in `dev` anymore.

**Comment by mimamuh** [comment]
@tonyganch Yes, thx. It seems it works! :)

**Comment by tonyganch** [comment]
@DanPurdy, seems like the issue was with broken `checkParentheses` function which was out of sync with `getParentheses`. Fixed for all syntaxes for parentheses and brackets, available in dev. Now the example from the first comment gets parsed and `($)` throws parsing error.
