### ISSUE TITLE
Specify structure of parsed Abstract Syntax Tree

### ISSUE THREAD

**Issue by eolognt** [tonyganch/gonzales-pe#202]
I found it hard to understand the structure of the AST that is created as you run the parsing function. I've understood that the tree is made up of nodes: one root node that could have zero, one or more child nodes that could have zero, one or more child nodes and so on (I guess every AST is constructed like this). But what does the node interface look like? To my understanding there isn't a standard AST structure for parsed CSS, which means I can't be sure the AST which is parsed by gonzales PE is the same as with for example the cssom parser (which is used here: https://astexplorer.net/). If there actually is a standard format for the AST, I would love to get a link to a spec for it.

**Comment by tonyganch** [comment]
Hey @eolognt!
This parser's AST is not compatible with cssom's one.

You can check out docs for all available node types and examples here: https://github.com/tonyganch/gonzales-pe/blob/dev/docs/node-types.md
Also, there is a playground for the parser here: http://tonyganch.com/gonzales-pe/
And some other explorer here: https://aslushnikov.github.io/gonzales-live/

Please keep in mind that playgrounds may (or may not) be a version or two late.

**Comment by tonyganch** [comment]
And regarding interface, all available methods and properties are described in readme: https://github.com/tonyganch/gonzales-pe#parsetreecontainstype
`parseTree` is any valid node.

**Comment by eolognt** [comment]
Hello @tonyganch! Thanks you, this was exactly what I was looking for :) Finding the documentation under the docs directory is perhaps pretty obvious, but maybe you should include these links anyway in the README? I think it is very helpful for newbies like me to have these tools. :)

**Comment by tonyganch** [comment]
Can you please help me with that a bit and send a PR? I think you're the best person to understand how to present those links in README so they are noticeable and helpful to newcomers :)

**Comment by eolognt** [comment]
Sure, would love to help! :)
