### ISSUE TITLE
SASS if function breaks parser

### ISSUE THREAD

**Issue by sathomas** [tonyganch/gonzales-pe#223]
```
.form__input {
    background-color: white if(not $css-reset, !important, unquote(""));
}
```

breaks the parser

Potential use case: http://stackoverflow.com/questions/39167183/scss-if-function-without-false-else-clause/

Blocking https://github.com/sasstools/sass-lint/issues/854

**Comment by tonyganch** [comment]
Hey @sathomas! I need some help with that issue so I can fix it correctly.
Where can `if()` function be used? Only as a value or basically anywhere (for example, to construct class name).
Also, do I get it right that second and third arguments can be anything at all?
I'll be very grateful for a link to source code of that function :)

**Comment by tonyganch** [comment]
The issue was with `!important` part not being parsed as a function argument.
I hotfixed that and released as `v3.4.7`.

**Comment by bgriffith** [comment]
Hey @tonyganch - Didn't https://github.com/tonyganch/gonzales-pe/pull/185 fix this?

**Comment by tonyganch** [comment]
@bgriffith, can you please rebase and merge it into `dev`? :)
