### ISSUE TITLE
Sass 3.5 on the horizon

### ISSUE THREAD

**Issue by DanPurdy** [tonyganch/gonzales-pe#229]
Im sure we're all aware that Sass 3.5 is on its way. Its currently waiting for libsass to get 3.4 parity before they push 3.5 but with the announcement of Dart Sass too it's possibly going to be arriving quicker than we thought.

http://blog.sass-lang.com/posts/809572-sass-35-release-candidate

Few new features we'll have to take into account here I assume.

**Comment by tonyganch** [comment]
Thanks for a heads-up!
Here is the list of new stuff I see, mainly about new CSS syntax than something specific to Sass:
- Custom property support - #197
- Named grid lines - #230

If you find something missing, please be so kind to open more issues? :)

**Comment by tonyganch** [comment]
I've checked their directory with tests and seems like the only thing there affecting the parser is ["Arguments can end with a comma"](https://github.com/sass/sass-spec/tree/master/spec/sass_3_5/arglists/can-end-with-comma), but we parse it okay already, so no additional work needed.
