### ISSUE TITLE
Identifiers with digits after underscore

### ISSUE THREAD

**Issue by tonyganch** [tonyganch/gonzales-pe#24]
From csscomb/csscomb.js#275:

``` scss
/*colors*/
$color_0: #fff;
$color_1: #285592;
$color_2: #86a9c2;
```

`$color_0` is parsed as a variable with ident `color_` without `0`.

**Comment by wvankuipers** [comment]
:+1:

**Comment by tonyganch** [comment]
Should be fixed in `dev`

**Comment by tdogg137** [comment]
Hello, I'm running into this same issue with a variable name $color-gray-light-20 and I'm wondering if the fixes have been in.  This is what I am using for the styleguide generator https://www.npmjs.com/package/sc5-styleguide#with-gulp

**Comment by wvankuipers** [comment]
@tonyganch Any news on when this will ship to master?
