### ISSUE TITLE
Issues with Interpolation

### ISSUE THREAD

**Issue by thejamespower** [tonyganch/gonzales-pe#243]
```
Unsupported beautification result 'Parsing error: Please check the validity of the block starting from line #31
31*| width: calc(100% - #{($variable / 2)});
Gonzales PE version: 3.0.0-28
Syntax: scss'.
```
The code is valid scss. Interestingly `width: calc(100% - #{$variable});` is fine.

A similar error occurs here:

```
Unsupported beautification result 'Parsing error: Please check the validity of the block starting from line #163

162 | @for $i from 0 through $sections { 163*| &--#{$i + 1} { 164 | .step { 165 | color: generate-reds($sections - $i);

Gonzales PE version: 3.0.0-28 Syntax: scss'.
```

Full block: 
```
  @for $i from 0 through $sections {
      &--#{$i + 1} {
        .step {
          color: generate-reds($sections - $i);
        }
      }
    }
```

**Comment by DanPurdy** [comment]
You're using an out of date version of Gonzales-pe, This error is already fixed in later versions. What package are you using which uses Gonzales-pe? The second example I'm not quite sure about now haven't got it tested. @bgriffith ?

**Comment by tonyganch** [comment]
> What package are you using which uses Gonzales-pe?

@DanPurdy, this looks like csscomb via atom-beautify, the latest stable version uses gpe@3.0.0

@thejamespower, both issues are fixed in the latest version of this parser, but I'm not sure when it will get to csscomb, sorry. I'll take a look what we can do.

Closing this issue as fixed.

**Comment by thejamespower** [comment]
@DanPurdy, @tonyganch, thanks for the heads up. Will await on CSSComb :)
