### ISSUE TITLE
Property interpolation causes a fatal error

### ISSUE THREAD

**Issue by abpetkov** [tonyganch/gonzales-pe#244]
Using double interpolation on a CSS property causes a fatal error.

Code that errors out:
```
.#{$spacing}-#{$orientation}-#{$type} { 
  #{$spacing}-#{$orientation}: $size !important; 
}
```

Code that works:
```
.#{$spacing}-#{$orientation}-#{$type} { 
  #{$spacing}: $size !important; 
}
```

**Comment by bgriffith** [comment]
Hey @abpetkov - Thanks for the report. You'll be pleased to hear that this is already fixed on develop, just waiting a release :+1:

**Comment by abpetkov** [comment]
@bgriffith that's good news! Please follow up on this issue when the release goes out and we can close it after that.

**Comment by bgriffith** [comment]
I'll close this now so I know it's fixed on dev, but will update the sass-lint issue once it's fixed in that too.
