### ISSUE TITLE
[Sass] Trailing newlines cause parse error

### ISSUE THREAD

**Issue by bgriffith** [tonyganch/gonzales-pe#246]
As of `v4`, trailing new lines in `sass` files cause the parser to fail.

![screen shot 2016-11-17 at 23 41 39](https://cloud.githubusercontent.com/assets/2854338/20412563/6609cfd4-ad1f-11e6-8e46-68366531d14c.png)

**Comment by bgriffith** [comment]
Possibly related, the following code is ok:

``` sass
.bar
    content: 'bar' // indented twice with 2 space
    content: 'baz' // indented with a single (2 space) tab
```

while the following code causes a parse error

``` sass
.bar
    content: 'bar'  // indented twice with 2 space
    content: 'baz'  // indented with a single (2 space) tab

.foo
  content: 'foo'
// ...etc
```

**Comment by tonyganch** [comment]
Here is the commit causing the issue: da531859a579ee7a56265824221c6ee7075599cb
I will have time to fix that only tomorrow, please add more examples if you find anything.

**Comment by tonyganch** [comment]
@bgriffith, fixed the original issue in dev and published as v4.0.2 :)
Please check and let me know how it goes.

**Comment by tonyganch** [comment]
Also updated playground with the current version: http://tonyganch.com/gonzales-pe/

**Comment by bgriffith** [comment]
Awesome thanks @tonyganch  - Only that remaining issue before we can move `sass-lint` over - https://travis-ci.org/sasstools/sass-lint/jobs/177008078.

Here's the direct link to the line with the issue - https://github.com/sasstools/sass-lint/blob/develop/tests/sass/indentation/indentation-spaces.sass#L38

**Comment by bgriffith** [comment]
Closing as this was fixed.
