### ISSUE TITLE
Parse scss file problem

### ISSUE THREAD

**Issue by fernando24164** [tonyganch/gonzales-pe#247]
I got an error while I was parsing scss.
This is the code line:

```
.dropdown-toggle {
  // The caret makes the toggle a bit too tall in IE7
  *margin-bottom: -3px;
}
```

The code is from here:
https://github.com/grafana/grafana/blob/v3.1.1/public/sass/components/_dropdown.scss#L13

Hope this can help. Thanks.

**Comment by tonyganch** [comment]
Hi @fernando24164, I'm sorry to say that I'm not planning to support hacks for older browser.
I believe it makes the parser depend on broken implementation and I would like to parse code according to stable specs.
I understand it will make it impossible for the parser and all the tools that are based on it to work with such code, but it will require more work to implement it properly than it will bring benefits.
