### ISSUE TITLE
Please check validity of the block starting from line Fatal

### ISSUE THREAD

**Issue by nithinankam** [tonyganch/gonzales-pe#255]
Forwarded from https://github.com/sasstools/sass-lint/issues/902

@keyframes #{pulsate}-#{$i} {
0% {
-webkit-transform: rotate($i) scale(1);
-moz-transform: rotate($i) scale(1);
-ms-transform: rotate($i) scale(1);
-o-transform: rotate($i) scale(1);
transform: rotate($i) scale(1);
}
50% {
-webkit-transform: rotate($i) scale(1.5);
-moz-transform: rotate($i) scale(1.5);
-ms-transform: rotate($i) scale(1.5);
-o-transform: rotate($i) scale(1.5);
transform: rotate($i) scale(1.5);
}
100% {
-webkit-transform: rotate($i) scale(1);
-moz-transform: rotate($i) scale(1);
-ms-transform: rotate($i) scale(1);
-o-transform: rotate($i) scale(1);
transform: rotate($i) scale(1);
}
}

What version of Sass Lint are you using?
V1.9.1
Actually, using https://www.npmjs.com/package/gulp-sass-lint which picks up 1.9.1
Please include any relevant parts of your configuration

What did you do? Please include the actual source code causing the issue.

What did you expect to happen?

What actually happened? Please include any error messages given to you by Sass Lint.

If you're using a IDE plugin have you tried the CLI too?

**Comment by bgriffith** [comment]
This should now be fixed in the latest release `v4.2.2`
