### ISSUE TITLE
Bug: Animation percents on separate lines causes fatal error

### ISSUE THREAD

**Issue by TheJaredWilcurt** [tonyganch/gonzales-pe#257]
Original issue is here:

* https://github.com/sasstools/sass-lint/issues/980

Reposting below for clarity:

* * *

**Version:** Latest (1.10.2)
**Code:**
```sass
@-webkit-keyframes spinner-rotate
    0%
        transform: rotateX(0deg) rotateY(0deg)
    80%
        transform: rotateX(365deg) rotateY(5deg)
    90%,
    100%
        transform: rotateX(360deg) rotateY(0deg)
```
**Error:**
```
Please check validity of the block starting from line #6 (Fatal)
```

This goes away if I put the `90%, 100%` on the same line. But that doesn't match the rest of my code, in which all comma separated selectors are on separate lines. And the `90%, 100%` being on separate lines has always been supported in `.sass` and `.scss`. So it shouldn't be causing a fatal error.

* [My .sass-lint.yml](https://github.com/TheJaredWilcurt/UGUI-pa11y/blob/master/.sass-lint.yml)
* [How I'm running Sass-Lint](https://github.com/TheJaredWilcurt/UGUI-pa11y/blob/master/sasslinter.js)

**Note:** If you have `single-line-per-selector` enabled, it will tell you that `90%, 100%` should be on separate lines, but when you put them on separate lines it causes a fatal error.

```
6:10  Selectors must be placed on new lines            (single-line-per-selector)
```

**Comment by bgriffith** [comment]
Fixed in latest version of gonzales-pe (4.2.2)
