### ISSUE TITLE
Make silent option available for node usage. Now is available only within the cli

### ISSUE THREAD

**Issue by DanielaValero** [tonyganch/gonzales-pe#259]
Hello,

In #222, the feature of printing the context when a parsing error happens was requested. However, this feature was intentionally removed from the default error message printing. At the moment is enabled in the `cli` by setting the option: `silent: false` when running `gonzales-pe` in the command line.

However the feature is not yet available within the `lib/`, so it is not possible to print the context of an error message when using `gonzales-pe` with node.

See related issues:

* #222 
* SC5/sc5-styleguide#1054

**Comment by tonyganch** [comment]
Spring cleaning of issue tracker 🧼
Closing this one as it was fixed with https://github.com/SC5/sc5-styleguide/commit/05b964f107fde3c26cac084174b96c4dd618c860
