### ISSUE TITLE
css variables

### ISSUE THREAD

**Issue by cancerberoSgx** [tonyganch/gonzales-pe#262]
Please support css variables like this: 

```

var css = ':root {\n	--color1: red;\n}'
var parseTree = parser.parse(css)

```

https://www.w3.org/TR/css-variables/

Thanks!, incredible project BTW !! :) :)

**Comment by tonyganch** [comment]
Hi @cancerberoSgx, I'm closing this issue as a duplicate of #197, please subsсribe there for updates.
