### ISSUE TITLE
Using a backslash for escaping raises an error

### ISSUE THREAD

**Issue by delijah** [tonyganch/gonzales-pe#265]
What version of Gonzales are you using?
3.4.7

What did you do? Please include the actual source code causing the issue.
I want to use ":global" (css-modules), ":import" (ICSS) and ":export" (ICSS) within my sass files.
To not raise an node-sass syntax error, i have to escape the ":" like so: "\:global".

```
\:export
    color: #303030
```

Related to: https://github.com/sasstools/sass-lint/issues/1066

What did you expect to happen?
Not raising an error. Since node-sass allows escaping the ":" at this place, gonzales should allow it as well.

What actually happened? Please include any error messages given to you by Sass Lint.
Gonzales sass parser throws an error.

**Comment by delijah** [comment]
Hey! Any news on this?

**Comment by delijah** [comment]
Is there any chance to have a fix soon? Or if you give me a hint in which code part this is checked/missing, i'll might be able to have a look or create a pull request by myself.

**Comment by delijah** [comment]
Unfortunately this code is too complex for me to find the related line of code by myself... any help would be appreciated.

**Comment by tonyganch** [comment]
Hi @delijah! First of all, sorry for not replying sooner.

Are you sure GPE has problems with your code? Could you please provide the full text of error you're getting?
I tried your code in playground (http://tonyganch.com/gonzales-pe/) and it's parsed just fine.

Anyway, the place in the code that's checking if next N characters are part of pseudoclass is here:
https://github.com/tonyganch/gonzales-pe/blob/dev/src/sass/parse.js#L3906

**Comment by bgriffith** [comment]
Is this still an issue? I can't seem to replicate. Do you have some more info on how to get this to error out? Thanks!

**Comment by bgriffith** [comment]
Closing for now.
