### ISSUE TITLE
SCSS: values in variables and extends throw error

### ISSUE THREAD

**Issue by luizotcarvalho** [tonyganch/gonzales-pe#27]
Any kind of value in variables and extends throw validity error.

Scss:

`
$background-16px: url(background-16px.png); 
`
or
`
@extend %background-16px;
`

throws:

`
Please check the validity of the block 
`

**Comment by RffaNunes** [comment]
I'm also with this problem!
I have not found a solution, can anyone help?

**Comment by vxsx** [comment]
looks related to https://github.com/csscomb/csscomb.js/issues/275

**Comment by tonyganch** [comment]
Should be fixed in `dev`
