### ISSUE TITLE
Property name CSS hacks for IE6/IE7 is discarded.

### ISSUE THREAD

**Issue by beatak** [tonyganch/gonzales-pe#29]
I'm not a big fan of CSS hacks for sure, and who cares IE6 and IE7… but I just stumbled upon this.

CSS:

```
.wtf {
  *overflow-x: hidden;
  //max-height: 110px;
  #height: 18px;
}
```

AST by gonzales-pe

```
["ruleset",
    ["selector",
        ["simpleselector",
            ["class", ["ident", "wtf"]],
            ["s", " "]]],
    ["block",
        ["s", "\n  "],
        ["declaration",
            ["property", ["ident","*overflow-x"]],
            ["propertyDelim"],
            ["s", " "],
            ["value", ["ident", "hidden"]]],
        ["declDelim"],
        ["s", "\n  "],
        ["commentSL", "max-height: 110px;"],
        ["s", "\n  "],
        ["declaration",
            ["property", ["ident", "height"]],
            ["propertyDelim"],
            ["s", " "],
            ["value",
                ["dimension",
                    ["number", "18"],
                    ["ident", "px"]]]],
        ["declDelim"],
        ["s", "\n"]]]
```

**Comment by tonyganch** [comment]
@beatak, and you propose what exactly?

**Comment by beatak** [comment]
Can `#height` be `#height` instead of `height`?

**Comment by JakeChampion** [comment]
It turns out this is now a fatal parsing error.
```scss
a {
	*display: inline;
}
```
>Error - Please check validity of the block starting from line #2 (Fatal)

If I work on enabling these browser hacks to be parsed successfully and not stripped from the generated CSS, would that be accepted?

**Comment by bgriffith** [comment]
Hey @JakeChampion - apologies for the delay. Been pondering whether to support browser hacks or not. In this instance I think we should and parse this hack as it has been so widely used. Happy to receive any PRs.

**Comment by jdalton** [comment]
IE6/7 are long past their support date so I'm going to close as `wontfix`. If there's strong user demand we'll reevaluate.
