### ISSUE TITLE
Publish v4.2.4

### ISSUE THREAD

**Issue by tonyganch** [tonyganch/gonzales-pe#294]
@srowhani has been patiently waiting for his #292 to be published for ages 🤦‍♂️

@jdalton, please 🐙

**Comment by srowhani** [comment]
@jdalton Could you also publish to npm?

**Comment by jdalton** [comment]
Hi @srowhani!

Yep. I'll update this issue when published. You can expect it published some time today. 

**Update:**

`gonzales-pe` [v4.2.4](https://github.com/tonyganch/gonzales-pe/blob/dev/CHANGELOG.md#22032019-version-424) is released 🎉

**Comment by jdalton** [comment]
**Update:**

`gonzales-pe` [v4.2.4](https://github.com/tonyganch/gonzales-pe/blob/dev/CHANGELOG.md#22032019-version-424) is released 🎉
