### ISSUE TITLE
throw new ParsingError(e, css)

### ISSUE THREAD

**Issue by weilinzung** [tonyganch/gonzales-pe#297]
An example that if I have `*display: inline;` that with an asterisk symbol.  Then it would cause errors:

```
/project/node_modules/gonzales-pe/lib/gonzales.js:816
	    throw new ParsingError(e, css);
	    ^
Parsing error: Please check validity of the block starting from line #31
```

That CSS framework is from a very old version of: https://github.com/csswizardry/inuit.css/blob/master/objects/_nav.scss

**Comment by jdalton** [comment]
Hi @weilinzung!

`gonzales-pe` doesn't support CSS hacks at the moment.
See #29. Feel free to revive the PR effort of #286 if you're up for adding support though 😅

**Comment by weilinzung** [comment]
@jdalton 

does this library has an ingore option then?

**Comment by jdalton** [comment]
@weilinzung I don't believe there's an ignore for this kind of error.
