### ISSUE TITLE
Invalid npm module version

### ISSUE THREAD

**Issue by vsn4ik** [tonyganch/gonzales-pe#32]
Hello!

Please, fix npm module version.
Invalid: 3.0.0-10.
Valid: 3.0.0.

**Comment by tonyganch** [comment]
`3.0.0-10` is a valid version.
It means that stable `3.0.0` version is not released yet and `3.0.0-10` is the tenth pre-release version.
Think of it as an alpha release.
See [Semantic Versioning Specification](http://semver.org/), paragraph 9 about pre-release versions.

**Comment by vsn4ik** [comment]
Thanks for https://github.com/csscomb/csscomb.js/commit/b68d62827265a69274c0a089ea21a150f01e7460.
