### ISSUE TITLE
srcToAst -> astToSrc создает дополнительные строки

### ISSUE THREAD

**Issue by varya** [tonyganch/gonzales-pe#34]
https://gist.github.com/varya/915847e2ec7b16e42d9e

**Comment by tonyganch** [comment]
Версия пакета + код, который всё ломает, пожалуйста.

**Comment by varya** [comment]
Пакет 3.0.0-10

Полный код https://github.com/varya/gonzales-try/tree/76cf35a09f5c54f0fafb29d2b9f64a2ece75824a

Минимальный для воспроизводства ошибки код:

```var gonzales = require('gonzales-pe'),
  fs = require('fs'),
  source = fs.readFileSync('_styleguide_variables.scss', 'utf-8');

var ast = gonzales.srcToAST({
  src: source,
  syntax: 'sass'
});

var result = gonzales.astToSrc({
  ast: ast,
  syntax: 'sass'
});

fs.writeFileSync('_styleguide_variables.scss', result);```

Если в каких-то ранних версиях пакета эта ошибка не воспроизводится, но они умеют srcToAst и astToSrc, то могу переключиться на них.

**Comment by tonyganch** [comment]
В дереве действительно не сохраняется информация о том, какой разделитель был в строке: перенос или точка с запятой. При переводе из дерева в строку вместо разделителя в любом случае подставляется перенос (отсюда и лишние строки). Это ошибка, которую нужно исправить. Спасибо.

**Comment by varya** [comment]
Уже понятно, когда это будет исправлено? Спрашиваю, чтобы запланировать свою работу.

**Comment by tonyganch** [comment]
Проверила: точка с запятой является невалидным разделителем в `sass` синтаксисе. То есть в объекте с опциями нужно передавать `syntax: 'scss'`, а не `syntax: 'sass'`. Посему закрываю тикет.
