### ISSUE TITLE
srcToAst c SASS контентом теряет ; в конце строк

### ISSUE THREAD

**Issue by varya** [tonyganch/gonzales-pe#35]

**Comment by tonyganch** [comment]
Я не умею ванговать по названию тикета.
Версия пакета + код, который падает + пример sass до и после, пожалуйста.

**Comment by varya** [comment]
https://github.com/tonyganch/gonzales-pe/issues/34

Ну это можно проверить просто попробовать что-то написать с npm install, рекомендованном в README. То есть с последней публичной версией пакета.

**Comment by tonyganch** [comment]
Закрываю как дубликат #34.
