### ISSUE TITLE
Preprocessors support

### ISSUE THREAD

**Issue by tonyganch** [tonyganch/gonzales-pe#4]
In order of importance:
- [x] scss
- [x] less
- [x] sass
- [ ] ~~stylus~~
- [ ] ~~roole~~

**Comment by miripiruni** [comment]
:+1:

**Comment by mishanga** [comment]
Roole is dead :(

**Comment by samosad** [comment]
:+1:

**Comment by paazmaya** [comment]
:+1:

**Comment by jamie-pate** [comment]
Um, so, any partial work on stylus? Trying to use SC5 styleguide generator + stylus :(

**Comment by tonyganch** [comment]
@jamie-pate, no, sorry, I'm not planning to add support for Stylus in near future.
[See this comment.](https://github.com/csscomb/csscomb.js/issues/159#issuecomment-48598982)

**Comment by darcyclarke** [comment]
Stylus should be pretty easy to support and or you can just use Stylus itself once [this Pull Request](https://github.com/stylus/stylus/pull/1915) goes through. I need Stylus support for my own project and noticed that, although they create an internal AST, they simply weren't exposing the object to the `render`'s callback.

Obviously the mappings/terminology may be different from what **gonzales** provides for the other languages, but it's a start.
