### ISSUE TITLE
SASS: Double parenthesis in functions are considerend to be invalid

### ISSUE THREAD

**Issue by varya** [tonyganch/gonzales-pe#43]
Where: current dev
Input:

```
$font-size-base: 3px;
.myclass {
  padding: cell(($font-size-base * 1.25));
}
``
Single test result:
```

/Users/varya/WebDev/SC5/gonzales-pe/lib/src-to-ast.js:15
        throw error;
              ^
Parsing error: Please check the validity of the block starting from line #2

1 | $font-size-large: 3px;
2*| $font-size-large: ceil(($font-size-base \* 1.25))

```

This syntax often used in Bootsrap https://github.com/twbs/bootstrap-sass/blob/d3531a6fded02ba8ecd3e2d1f987927bd414883b/assets/stylesheets/bootstrap/_variables.scss#L57 and is considered to be valid by http://sassmeister.com/
```

**Comment by varya** [comment]
Covered in PR #45

**Comment by tonyganch** [comment]
#45 has been merged into `dev`
