### ISSUE TITLE
SASS: != operator is considered to be invalid

### ISSUE THREAD

**Issue by varya** [tonyganch/gonzales-pe#44]
Where: current dev.
Input:

```
$bootstrap-sass-asset-helper: (twbs-font-path("") != unquote('twbs-font-path("")')) !default;
```

Output:

```
/Users/varya/WebDev/SC5/gonzales-pe/lib/src-to-ast.js:15
        throw error;
              ^
Parsing error: Please check the validity of the block starting from line #1

1*| $bootstrap-sass-asset-helper: (twbs-font-path("") != unquote('twbs-font-path("")')) !default;
```

This code is used in Bootsrap https://github.com/twbs/bootstrap-sass/blob/d3531a6fded02ba8ecd3e2d1f987927bd414883b/assets/stylesheets/bootstrap/_variables.scss#L4 and is considered to be valid by http://sassmeister.com/

`==` works normally

**Comment by varya** [comment]
Covered in PR #46

**Comment by tonyganch** [comment]
Closing since #46 is merged into `dev`
