### ISSUE TITLE
Traverse is needed

### ISSUE THREAD

**Issue by varya** [tonyganch/gonzales-pe#50]
Do you think it is possible and suitable to implement `traverse` as a part of this package? I currently use `gonzales-ast` but as it was built by the time when Gonzales could only parse CSS, it can be sometimes buggy. This is an example of what I mean https://github.com/stoyan/gonzales-ast/pull/1

Having a traverse method together with the parser would guarantee the compatibility for new versions.

**Comment by tonyganch** [comment]
It's possible and of course we should do this. But first I need to finish replacing old array-based ast with objects.

**Comment by tonyganch** [comment]
`ast.map()`: https://github.com/tonyganch/gonzales-pe/tree/dev#astmapfunction
I have no strong opinion on how the method should be called, so if you want it named `traverse` or need some changes, let me know.

**Comment by varya** [comment]
Looks OK. Could you release 3.0.0-13?

**Comment by tonyganch** [comment]
@varya, published. But please note new AST format.
