### ISSUE TITLE
Improvements to .map method needed (v 3.0.0) 

### ISSUE THREAD

**Issue by varya** [tonyganch/gonzales-pe#51]
I tried new `.map` method and it looks like it needs to be improved. For example, this is the code I use to grab all the variables from the source and their values.

```
  ast.map(function(node) {
    if (node.type !== 'declaration') {
      return;
    }
    var variable = {}
    ast.map.call(node, function(nnode){
      if (nnode.type === 'variable') {
        ast.map.call(nnode, function(nnnode){
          if (nnnode.type === 'ident') {
            variable.name = nnnode.content;
          }
        });
      }
      if (nnode.type === 'value') {
        variable.value = nnode.toCSS(syntax);
      }
    });
    out.push(variable);
  });
```

It turns out to be very messy code when I need to get deeper into the structure. I think something like json-path is needed here. Do you think it is possible to embed any path-router into Gonzales? Or maybe you can recommend to use a ready-made pather and mention this in the documentation?

**Comment by tonyganch** [comment]
Would this be better?

```
ast.forEach('declaration', function(declaration) {
  declaration.forEach('variable', function(node) {
    variable.name = node.find('ident').content;
  });

  declaration.forEach('value', function(node) {
    variable.value = node.toCSS(syntax);
  });
});
```

Two new methods:
1) `ast.forEach(type, callback)` calls a function for each node of a given type
2) `ast.find(type)` returns the first child of a given type

**Comment by tonyganch** [comment]
@varya, as for your example above, `ast.map.call(node, function)` can be replaced with just `node.map(function)` since `.map()` method is available for every node (including children).

**Comment by varya** [comment]
Thanks. `forEach` and `find` look good.
Also, mind you. I needed to grab all the variables mentioned in values and I did this with `jspath` this way:

```
var out = jspath.apply('..content{.type === "value" }..content{.type === "variable" }..content{.type === "ident"}.content', ast);
```

As I see, `forEach` and `find` will help here too.

**Comment by tonyganch** [comment]
> jspath.apply('..content{.type === "value" }..content{.type === "variable" }..content{.type === "ident"}.content', ast);

It looks like magic to me :)

**Comment by varya** [comment]
Am I right that my problem can now be solved with `ast.forEach` and `ast.first`?

**Comment by tonyganch** [comment]
Here is what I get:

``` js
var css = '$color: tomato; a {color: $panda}';
var ast = gonzales.parse(css, {syntax: 'scss'});

var variables = [];
ast.map(function(declaration) {
    if (!declaration.is('declaration')) return;

    var property = declaration.first('property');
    if (property.contains('variable')) {
        variables.push({
            name: property.toCSS('scss'),
            value: declaration.first('value').toCSS('scss')
        });
    }
});
console.log(variables); // logs `[ { name: '$color', value: 'tomato' } ]`
```

Is it ok for you?

**Comment by varya** [comment]
We will try the new methods and give our feedback in a while.

**Comment by tonyganch** [comment]
@varya, can the issue be closed?
