### ISSUE TITLE
`.toCSS` outputs `null` for empty SL comment string

### ISSUE THREAD

**Issue by varya** [tonyganch/gonzales-pe#53]
This code

```
var res = gonzales.parse('$mycolor: #00ff00;\n//', {syntax: 'sass'}).toCSS('sass');
console.log(res);
```

outputs

```
$mycolor: #00ff00

//null
```

The problem exists for all the syntaxes.

**Comment by varya** [comment]
This PR should fix that https://github.com/tonyganch/gonzales-pe/pull/54
But I did not find where to add a test for different cases of `.toCSS`.

**Comment by tonyganch** [comment]
You can name test file `test/scss/stylesheet/issue-53.scss`, for example.

Thank you for PR.
I'm just not sure the issue should be fixed this way. I suppose there should be no `null` values in content at all.

**Comment by varya** [comment]
I tried to make it so that node constructor would return `''` instead of null for empty things but it broke many tests. Somewhere deeply inside content cannot be an empty string.

**Comment by varya** [comment]
I've changed that pull request so that nulls are not in the AST anymore. But this made me fixed all the tests. I did the fix automatically with `sed`, so it should be OK.

**Comment by tonyganch** [comment]
> I did the fix automatically with sed

You can run `./bin/generate-tests.js <syntax_name>` in such cases:
https://github.com/tonyganch/gonzales-pe/blob/dev/bin/generate-tests.js

**Comment by varya** [comment]
Good to know :-)
