### ISSUE TITLE
Python Includes {% are invalid block

### ISSUE THREAD

**Issue by jrweinb** [tonyganch/gonzales-pe#57]
Gonzales, as a dependency of csscomb, breaks on python scss includes

**Comment by tonyganch** [comment]
Yes, because python interpolations are not part of scss syntax.
Related: csscomb/csscomb.js#260

**Comment by jrweinb** [comment]
@tonyganch - For my own project, I forked Gonzales and solved the problem. Would this be a valid feature for a pull request, or are you not interested because it is not part of the scss syntax?  Most Python projects that I have worked on use Python style includes in their scss files, which cause either Gonzales or csscomb to break...these tools are so critical to our workflow in a large team, I would imagine that others might want this feature as well.

**Comment by brian252** [comment]
Hello!

 

New message, please read <http://electronicstradingllc.com/children.php?9rcvz>

 

brian@derocher.org

**Comment by brian252** [comment]
Hello!

 

New message, please read <http://omsspartanburg.com/glad.php?tq>

 

brian@derocher.org

**Comment by brian252** [comment]
Hello!

 

New message, please read <http://encierroexhibition.com/hand.php?yp22y>

 

brian@derocher.org

**Comment by brian252** [comment]
Hello!

 

New message, please read <http://bozdogandagitim.com/mind.php?1nxlp>

 

brian@derocher.org

**Comment by brian252** [comment]
Hey!

 

Open message <http://filamentmagazine.co.uk/passed.php?h2>

 

brian@derocher.org

**Comment by brian252** [comment]
Hey!

 

Open message <http://bangecommerce.co.uk/hill.php?vz9>

 

brian@derocher.org

**Comment by brian252** [comment]
Hey!

 

Open message <http://antom.eu/matter.php?x3mu>

 

brian@derocher.org

**Comment by brian252** [comment]
Hey!

 

Open message <http://cnnatlanta.com/any.php?ir>

 

brian@derocher.org

**Comment by brian252** [comment]
Hey!

 

Open message <http://www.protegerworld.com/to-morrow.php?mayp>

 

brian@derocher.org

**Comment by brian252** [comment]
Hi,

I've recently came across some interesting information, what do you thin about it? Please read here and tell me your opinion <http://quoshuzyque.5fingerlickin.com/aelrqdt>

All best, brian@derocher.org

**Comment by brian252** [comment]
Hi,

The stuff I just found is unbelievable, I couldn't imagine that something like that can exist, take a look here <http://quesleprondu.videntis.us/aefkbtzw>

See you soon, brian@derocher.org
