### ISSUE TITLE
Sass variable parsing error

### ISSUE THREAD

**Issue by junaidrsd** [tonyganch/gonzales-pe#59]
This is valid SASS LESS syntax should be parsed without problem
Parsing error: Please check the validity of the block starting from line 23

23\* | $palette-color-1: #ffcf3c;

Gonzales PE version: 3.0.0-16
Syntax: scss

**Comment by varya** [comment]
In SASS ending `;` is not allowed. You can check it here http://sassmeister.com/ (choose SASS, not SCSS in the preferences of the page). With that you will get `Invalid CSS after "#ffcf3c": expected expression (e.g. 1px, bold), was ";"`

**Comment by junaidrsd** [comment]
The problem is not semicolon here the problem starts with variable name ending with '-digit' in this case $palette-color-1. which is acceptable by SASS, SCSS and LESS but gonzales-pe is not accepting it. It seems issue has been fixed in dev.

**Comment by tonyganch** [comment]
Fixed in `dev`, available as version `3.0.0-27`
