### ISSUE TITLE
#{} interpolation does not work with @media query

### ISSUE THREAD

**Issue by hannu** [tonyganch/gonzales-pe#60]
Gonzales-pe is unable to parse definition when #{} interpolation is used with the media query
The following input breaks the parsing:

```
$medium: "screen and (min-width: 600px)";
@media #{$medium} {
}
```

```
     Please check the validity of the block starting from line #2

1 |           $medium: "screen and (min-width: 600px)";
2*|           @media #{$medium} {
3 |           }

Gonzales PE version: 3.0.0-26
Syntax: scss
```

**Comment by ivnmaksimovic** [comment]
+1

**Comment by tonyganch** [comment]
Should be fixed in `dev`, available via `3.0.0-27`

**Comment by ghost** [comment]
@tonyganch can you please explain, how one can install 3.0.0-27? There is no release with this version and I don't know how to build npm projects.

**Comment by tonyganch** [comment]
@thomas-koch-comsolit, you can install it with `npm install gonzales-pe@3.0.0-27`.
But can I ask you to wait for two weeks for a stable 3.0 release instead? I will remove all beta `3.0.0-xx` versions from npm then.
