### ISSUE TITLE
[scss] Interpolations

### ISSUE THREAD

**Issue by tonyganch** [tonyganch/gonzales-pe#68]
Interpolations should be parsed correctly almost everywhere when `ident` is ok.

https://github.com/csscomb/csscomb.js/issues/271

**Comment by mel0mani4** [comment]
Hello, do you know when this issue will be fixed ? Because it prevents me from using SC5 Styleguide Generator on my platform :'(
Thank you very very much in advance...

**Comment by tonyganch** [comment]
@mel0mani4, can you give me a sample code that fails for you, please? It'll help me write a test and fix this issue faster.

**Comment by mel0mani4** [comment]
I had this problem by adding KNACSS and Bourbon code in my project.

Every interpolated variables inside braces (not as selectors) gave me errors, whether it is the "TypeError:
Cannot call method 'toCSS' of undefined" (with KNACSS' interpolations inside braces, in
its _03-grids.scss file) or simply "Parsing error: Please check the validity of the block starting from line #68" (with all the Bourbon interpolations inside braces).

Just try to install Bourbon in your project, and you'll see :)

**Comment by igoratron** [comment]
It seems to me gonzales is struggling to understand interpolated property names. See the following SCSS example:

```
.test { 
  $property: color; 
  #{$property}: black; 
}
```

Running this through gonzales throws `Error: Please check the validity of the CSS block starting from the line #1`. Any thoughts on this?

**Comment by danoc** [comment]
Also running into the issue that @igoratron described. Has anyone looked into it? I'm exploring a fix.

**Comment by danoc** [comment]
Pretty sure I found the fix. Will write some tests and submit a PR in the next few days.

**Comment by karlhorky** [comment]
I would like this to be fixed as well. @danoc did you get any further with the fix?

**Comment by danoc** [comment]
@karlhorky – Just created a PR with the fix. https://github.com/tonyganch/gonzales-pe/pull/80

**Comment by karlhorky** [comment]
Awesome, thanks!

**Comment by tonyganch** [comment]
Fixed in `dev` :cherries:

**Comment by karlhorky** [comment]
Thanks @tonyganch !

**Comment by igoratron** [comment]
Excellent news, @tonyganch! Any idea when this will be released?

**Comment by danoc** [comment]
Thanks for all the hard work, @tonyganch! 

Have you written/spoken about this project? I'd love to learn more about it.

**Comment by cgtm** [comment]
@tonyganch I'm running the dev branch (currently 3.0.0-31) and I'm seeing the same problem as @igoratron did above. Specifically, the following code produces an error with the same message as Igor's.

```
a {
  $attribute: background-color;
  $color: #aaa;
  #{$attribute}: $color;
}
```

You message above implies this should be fixed now. Is there a more recent version than the one I'm using? Many thanks for any help.

Further: more digging shows my gonzales-pe/lib/scss/parse.js doesn't have, for example, checkIdentOrInterpolation() whereas gonzales-pe/blob/dev/src/scss/parse.js defines it.

**Comment by ivnmaksimovic** [comment]
Same here with 3.0.0-31.
Parsing error: Please check validity of the block starting from line #7

`left: calc(50% - #{$logo-width / 2});`

Syntax: scss
Gonzales PE version: 3.0.0-31

**Comment by DanPurdy** [comment]
@ivnmaksimovic this is fixed in the latest versions of gonzales-pe

``` scss
.test {
  left: calc(50% - #{$logo-width / 2});
}
```

```
 -> stylesheet
 | -> ruleset
 | | -> selector
 | | | -> class
 | | | | -> ident
 | | | |    "test"
 | | -> space
 | |    " "
 | | -> block
 | | | -> space
 | | |    "\n"
 | | | -> declaration
 | | | | -> property
 | | | | | -> ident
 | | | | |    "left"
 | | | | -> propertyDelimiter
 | | | |    ":"
 | | | | -> space
 | | | |    " "
 | | | | -> value
 | | | | | -> function
 | | | | | | -> ident
 | | | | | |    "calc"
 | | | | | | -> arguments
 | | | | | | | -> percentage
 | | | | | | | | -> number
 | | | | | | | |    "50"
 | | | | | | | -> space
 | | | | | | |    " "
 | | | | | | | -> operator
 | | | | | | |    "-"
 | | | | | | | -> space
 | | | | | | |    " "
 | | | | | | | -> interpolation
 | | | | | | | | -> variable
 | | | | | | | | | -> ident
 | | | | | | | | |    "logo-width"
 | | | | | | | | -> space
 | | | | | | | |    " "
 | | | | | | | | -> operator
 | | | | | | | |    "/"
 | | | | | | | | -> space
 | | | | | | | |    " "
 | | | | | | | | -> number
 | | | | | | | |    "2"
 | | | -> declarationDelimiter
 | | |    ";"
 | | | -> space
 | | |    "\n"
```

**Comment by ivnmaksimovic** [comment]
@DanPurdy ok. Thanks. I am using SC5 styleguide, but haven't updated it...
