### ISSUE TITLE
Update docs to match current codebase

### ISSUE THREAD

**Issue by gmac** [tonyganch/gonzales-pe#69]
I think I'm using v3.0 correctly, although it's difficult to say for sure.

**Comment by tonyganch** [comment]
v3.0 is unstable and not published yet: `3.0.0-x` versions are released for testing purpose only.
API is still about to change and you should not actually rely on it.
I'll update docs once stable version is out.

**Comment by gmac** [comment]
:+1: thanks, and good work on this parser!
