### ISSUE TITLE
Wrong property-value recognistion in sass

### ISSUE THREAD

**Issue by goganchic** [tonyganch/gonzales-pe#79]
In such simple sass code fragment:

```
.service-info-registration
  fieldset:last-child
    margin-top: 60px
```

if there is no space between ':' and property value - these tokens should be a selector, but now it is recognised as property and value. So, parser produces wrong AST.
I looked at original ruby sass, and http://sass-lang.com/ site and found that in your sass code you have to add space after ':' if it is a property-value pair. If you skip space - line should be recognised as selector.
There are a lot of wrong test cases like test/sass/ruleset/0.sass where you have skipped space between colon and value.

**Comment by tonyganch** [comment]
I tried it here: http://sassmeister.com/

``` sass
// Source
.a
    color:red
    div
      color:green

// Compiled to
.a {
  color: red;
}

.a div {
  color: green;
}
```

**Comment by tonyganch** [comment]
And one more example:

``` sass
// Source
.service-info-registration
  fieldset:last-child
  margin-top: 60px

// Compiled to
.service-info-registration {
  fieldset: last-child;
  margin-top: 60px;
}
```

I guess the only thing that helps you define a selector is a nested block.
I'll take a look at tests, thank you for noticing.

**Comment by goganchic** [comment]
And what if you have no nested block?

```
.service-info-registration
  fieldset:last-child
```

what is it? selector or property-value pair? Ruby sass says that it is an empty selector.

**Comment by goganchic** [comment]
```
// Source
.a
    div
    color:green
```

gives error "property "div" must be followed by a ':' on line 2 at column 5" (it detects property, not selector) with libsass and outputs nothing with sass 3.4.14 (WARNING on line 2: This selector doesn't have any properties and will not be rendered. WARNING on line 3: This selector doesn't have any properties and will not be rendered.) - it detects selectors on line 2 and 3. So, libsass & ruby sass works differently.

**Comment by tonyganch** [comment]
As for original example:

``` sass
.service-info-registration
  fieldset:last-child
    margin-top: 60px
```

Here is a simplified tree, from `dev` branch:

```
 -> stylesheet
 | -> ruleset
 | | -> selector
 | | | -> simpleSelector
 | | | | -> class
 | | | | | -> ident
 | | | | |    "service-info-registration"
 | | -> space
 | |    "\n"
 | | -> block
 | | | -> space
 | | |    "  "
 | | | -> ruleset
 | | | | -> selector
 | | | | | -> simpleSelector
 | | | | | | -> ident
 | | | | | |    "fieldset"
 | | | | | | -> pseudoClass
 | | | | | | | -> ident
 | | | | | | |    "last-child"
 | | | | -> space
 | | | |    "\n"
 | | | | -> block
 | | | | | -> space
 | | | | |    "    "
 | | | | | -> declaration
 | | | | | | -> property
 | | | | | | | -> ident
 | | | | | | |    "margin-top"
 | | | | | | -> propertyDelimiter
 | | | | | |    ":"
 | | | | | | -> space
 | | | | | |    " "
 | | | | | | -> value
 | | | | | | | -> dimension
 | | | | | | | | -> number
 | | | | | | | |    "60"
 | | | | | | | | -> ident
 | | | | | | | |    "px"
 - - - - - - - -
```

As you can see, `fieldset:last-child` gets parsed as a selector.
So I'm closing the issue as fixed in `dev`.

**Comment by goganchic** [comment]
Thanks a lot!
