### ISSUE TITLE
Sass variable interpolation breaks parser

### ISSUE THREAD

**Issue by varya** [tonyganch/gonzales-pe#86]
A error is thrown for SASS syntax. Gonzales-PE, version 3.0.*

Parsing error: Please check validity of the block starting from line #247

```
246 | @mixin placeholderColor($element, $color)
247*|   #{$element}::-webkit-input-placeholder
248 |       color: $color
```

Seems that the parser does not support sass variable interpolation.

**Comment by varya** [comment]
Duplicate of https://github.com/tonyganch/gonzales-pe/issues/31

**Comment by tonyganch** [comment]
This is not a duplicate, I'll take a look

**Comment by tonyganch** [comment]
Should be ok in `dev` branch

**Comment by cgtm** [comment]
@tonyganch Would this issue also be present for scss format? If yes, does the commit above cover scss?

**Comment by tonyganch** [comment]
@cgtm, the issue with pseudo-elements didn't affect scss files. So no, this fix is not valid for scss format.
Do you have trouble with interpolations in scss? Here are some related issues:
https://github.com/tonyganch/gonzales-pe/search?q=interpolation&type=Issues&utf8=✓
