### ISSUE TITLE
Nested Traverse

### ISSUE THREAD

**Issue by Snugug** [tonyganch/gonzales-pe#87]
I'm working on writing a linter based off of this and I've run in to an issue; there is a need to be able to traverse a node all the way down the tree. Currently, `forEach` and `contains` only works for a given node's first-level content, but not all the way down the tree, meaning that if I want to find a node deeply nested inside a specific node, I can't.

Take, for example, nested selectors in Sass and the following code:

``` scss
.foo {
  content: bar;

  .baz {
    content: qux;
  }
}
```

In this scenario, I'd like search for all selectors and see if their parent's `block` contains selectors, all the way down. Currently, there is no quick way to do this for a depth of `n` but seems like that would be a useful function. Something like `parent.first('block').traverseByType('selector')` to traverse all the way down the tree of that `block` node in the tree.

**Comment by tonyganch** [comment]
You can now accomplish this with:

``` js
parent.traverse(function(child) {
  if (child.type !== 'selector') return;
  // Do something with selector here.
});
```

Is this enough, or you still need `traverseByType` function?

**Comment by tonyganch** [comment]
Please-please be careful with `dev` branch, because api still can change a bit.

**Comment by Snugug** [comment]
`traverseByType` would be nice for my use case, but not required.

Thanks for the warning; I'll be sure to lock to known good versions. And thanks for your work!

**Comment by Snugug** [comment]
I've got this working. Thanks!
