### ISSUE TITLE
AST documentation?

### ISSUE THREAD

**Issue by alebelcor** [tonyganch/gonzales-pe#9]
Is there any documentation on the AST produced when parsing SCSS?

I'm having a hard time interpreting how that tree is read and how to use it.

Thanks!

**Comment by tonyganch** [comment]
It's partially documented here: [AST description](https://github.com/tonyganch/gonzales-pe/blob/master/doc/AST-Description.md)
Do you have any specific questions?
I'll try to help.

**Comment by alebelcor** [comment]
This is great.

I immediately went looking for the wiki pages but found none. I didn't realize there was a `doc` folder in the repo.

Thanks!

**Comment by tonyganch** [comment]
I'm closing the issue if you have no further questions.
