### ISSUE TITLE
Brace Node Type

### ISSUE THREAD

**Issue by Snugug** [tonyganch/gonzales-pe#90]
I may have [missed it](https://github.com/tonyganch/gonzales-pe/blob/dev/doc/node-types.md) but I'm looking for a brace node type for my Sass Lint project in order to provide linting around it. Is there one that I've missed? If not, may I request one be added?

Thank you!

**Comment by tonyganch** [comment]
`braces` were renamed to `brackets` (`[]`) and `parentheses` (`()`). Also there are `arguments` which assume there are parentheses around.
Does this answer your question?

**Comment by tonyganch** [comment]
Some links to tests as examples:
- arguments: https://github.com/tonyganch/gonzales-pe/tree/dev/test/scss/arguments
- brackets: https://github.com/tonyganch/gonzales-pe/tree/dev/test/scss/brackets
- parentheses: https://github.com/tonyganch/gonzales-pe/tree/dev/test/scss/parentheses

**Comment by tonyganch** [comment]
I'm very sorry that documentation in `dev` branch is still so poor :(

**Comment by Snugug** [comment]
I'm specifically looking for curly braces {} and where they occur in the document.

Once I get my initial release out the door I'm happy to help with documentation.

**Comment by tonyganch** [comment]
Oh, there is no `braces` type, sorry.
There are: `block`, `atruleb` and `atruler`.

**Comment by Snugug** [comment]
May I request a `braces` type then?

**Comment by tonyganch** [comment]
And you can't use `block`, because... ?
I'm bad at describing things maybe, `atruleb` and `atruler` both have `block` inside.
So `block` == basically anything inside `{...}`, no matter where you meet it.
That's what you need, right? Or do I miss something?

**Comment by Snugug** [comment]
I specifically need the location of the `{}` so I can understand where they're placed and what's surrounded by them. I can look at `block` and see if I can parse the info I need from that.

**Comment by tonyganch** [comment]
Here is csscomb's implementation of "space before an opening brace":
https://github.com/csscomb/csscomb.js/blob/dev/src/options/space-before-opening-brace.js#L39
Maybe it will be of some help to you.

**Comment by Snugug** [comment]
Yah, I can probably work off of that. Prefer not to make assumptions where possible, but yah I can do that.

Thank you!
