### ISSUE TITLE
package.json has incorrect "main" field

### ISSUE THREAD

**Issue by benthemonkey** [tonyganch/gonzales-pe#97]
The `lib` folder no longer exists in the `dev` branch. Should it point to the `src` folder?

**Comment by tonyganch** [comment]
Nope. `lib` appears once you run `npm run build`, which triggers babel. I assume that when you run `npm install gonzales-pe`, built files are downloaded instead of source.

**Comment by benthemonkey** [comment]
Oops. Sorry about that. Maybe this issue will help reduce future confusion.
